name: Docker Image CI

on:
  push:
    branches: [ "**_deploy", "main" ]
  pull_request:
    branches: ["**_deploy", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with:
#        context: .
#        file: ./Dockerfile
        run: |
          docker build  \
          --ssh default=${{ secrets.SSH_PRIVATE_KEY }} \
          --build-arg GIT_BRANCH=${{ steps.extract_branch.outputs.branch }} \
          --tag winword_microservice:$(date +%s) .
        ssh: |
          default=${{ env.SSH_AUTH_SOCK }}
        push: true
        tags: s3docker.francissecada.com/winword_microservice:${{ steps.extract_branch.outputs.branch }}.${{ steps.date.outputs.date }}
